# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS += "evb-raspberrypi"
BBFILE_PATTERN_evb-raspberrypi = ""
BBFILE_PATTERN_IGNORE_EMPTY_evb-raspberrypi = "1"
LAYERSERIES_COMPAT_evb-raspberrypi = "walnascar scarthgap"
